@extends('layouts.landing')
@section('content')


    <section class="pricing-area ptb-100 extra-mb pb-0"
             style="margin-bottom: 100px!important;background: rgba(211,211,211,0.15);padding-bottom: 30px!important;">
        <div class="container">
            <h2>Acceptable Use Policy</h2>
        </div>
    </section>



    <section class="services-area">
        <div class="container">
            <p>

                Eagle Internet’s Acceptable Use Policy
                <br>
                <br>
                All business and residential Eagle Internet customers (the “customer,” “user,” “you,” or “your”) and all others who use the Service must comply with this Policy. Your failure, or others’ failure, to comply with this Policy could result in the suspension or termination of your or their Service accounts. Therefore, you should take steps to ensure that others you permit to use your Service are aware of this Policy and agree to abide by it. If you are unwilling to comply with this Policy, you must immediately stop all use of the Service and notify Eagle Internet so that it can close your account. This policy is in addition to, and supplements, all other Eagle Internet agreements.This Policy applies to your use of the Service if you are a business or residential EAGLE INTERNET customer who accesses Eagle Internet -provided services inside or outside of your premises or in public places using an EAGLE INTERNET account.
                Eagle Internet may revise this Policy from time to time by posting a new version on the web site at get eagleinternetservices.com/AUP or any successor URL(s) (the “EAGLE INTERNET Web site”). Eagle Internet will use reasonable efforts to make customers aware of any changes to this Policy, which may include sending email announcements or posting information on the EAGLE INTERNET Web site. Revised versions of this Policy are effective immediately upon posting. Accordingly, customers of the Service should read any Eagle Internet announcements they receive and regularly visit the EAGLE INTERNET Web site and review this Policy to ensure that their activities conform to the most recent version. <br>
                I. Prohibited Uses and Activities <br>
                In general, Eagle Internet prohibits uses and activities involving the Service that are illegal, infringe the rights of others, or interfere with or diminish the use and enjoyment of the Service by others. For example, these prohibited uses and activities include, but are not limited to, using the Service, Customer Equipment, or the Eagle Internet Equipment, either individually or in combination with one another, to:
                <br>A. Conduct and information restrictions undertake or accomplish any unlawful purpose. This includes, but is not limited to, posting, storing, transmitting or disseminating information, data or material which is libelous, obscene, unlawful, threatening or defamatory, or which infringes the intellectual property rights of any person or entity, or which in any way constitutes or encourages conduct that would constitute a criminal offense, or otherwise violate any local, state, federal, or non-U.S. law, order, or regulation;
                post, store, send, transmit, or disseminate any information or material which a reasonable person could deem to be unlawful; upload, post, publish, transmit, reproduce, create derivative works of, or distribute in any way information, software or other material obtained through the Service or otherwise that is protected by copyright or other proprietary right, without obtaining any required permission of the owner;
                transmit unsolicited bulk or commercial messages commonly known as “spam;” <br>
                send very large numbers of copies of the same or substantially similar messages, empty messages, or messages which contain no substantive content, or send very large messages or files that disrupts a server, account, blog, newsgroup, chat, or similar service;
                initiate, perpetuate, or in any way participate in any pyramid or other illegal scheme;
                participate in the collection of very large numbers of email addresses, screen names, or other identifiers of others (without their prior consent), a practice sometimes known as spidering or harvesting, or participate in the use of software (including “spyware”) designed to facilitate this activity;
                collect responses from unsolicited bulk messages;falsify, alter, or remove message headers;
                falsify references to Eagle Internet or its network, by name or other identifier, in messages;
                impersonate any person or entity, engage in sender address falsification, forge anyone else’s digital or manual signature, or perform any other similar fraudulent activity (for example, “phishing”);
                violate the rules, regulations, terms of service, or policies applicable to any network, server, computer database, service, application, system, or web site that you access or use; <br>
                B. Technical restrictions access any other person’s computer or computer system, network, software, or data without his or her knowledge and consent; breach the security of another user or system; or attempt to circumvent the user authentication or security of any host, network, or account. This includes, but is not limited to, accessing data not intended for you, logging into or making use of a server or account you are not expressly authorized to access, or probing the security of other hosts, networks, or accounts without express permission to do so; use or distribute tools or devices designed or used for compromising security or whose use is otherwise unauthorized, such as password guessing programs, decoders, password gatherers, keystroke loggers, analyzers, cracking tools, packet sniffers, encryption circumvention devices, or Trojan Horse programs. Unauthorized port scanning is strictly prohibited;
                copy, distribute, or sublicense any proprietary software provided in connection with the Service by Eagle Internet or any third party, except that you may make one copy of each software program for back-up purposes only; distribute programs that make unauthorized changes to software (cracks);
                use or run dedicated, stand-alone equipment or servers from the Premises that provide network content or any other services to anyone outside of your Premises local area network (“Premises LAN”), also commonly referred to as public services or servers. Examples of prohibited equipment and servers include, but are not limited to, email, web hosting, file sharing, and proxy services and servers;
                use or run programs from the Premises that provide network content or any other services to anyone outside of your Premises LAN, whether for personal or commercial use;
                service, alter, modify, or tamper with the Eagle Internet Equipment or Service or permit any other person to do the same who is not authorized by Eagle Internet; <br>
                C. Network and usage restrictions <br>
                use the Service for operation as an Internet service provider or for any business, other legal entity, or organization purpose (whether or not for profit);
                restrict, inhibit, or otherwise interfere, regardless of intent, purpose or knowledge, with the ability of any other person to use or enjoy the Service (except for tools for safety and security functions such as parental controls, for example), including, without limitation, posting or transmitting any information or software which contains a worm, virus, or other harmful feature, or
                impede others’ ability to use, send, or retrieve information;
                restrict, inhibit, interfere with, or otherwise disrupt or cause a performance degradation, regardless of intent, purpose or knowledge, to the Service or any Eagle Internet (or Eagle Internet supplier) host, server, backbone network, node or service, or otherwise cause a performance degradation to any Eagle Internet (or Eagle Internet supplier) facilities used to deliver the Service;
                resell the Service or otherwise make available to anyone outside the Premises the ability to use the Service (for example, through the Eagle Internet network), in whole or in part, directly or indirectly, with the sole exception of your use of the Eagle Internet network in accordance with its then-current terms and policies; connect the Eagle Internet Equipment to any computer outside of your Premises;
                interfere with computer networking or telecommunications service to any user, host or network, including, without limitation, denial of service attacks, flooding of a network, overloading a service, improper seizing and abusing operator privileges, and attempts to “crash” a host; or<br>
                II. Customer Conduct and Features of the Service
                <br>You are responsible for your own compliance with this Policy. You are also responsible for any use or misuse of the Service that violates this Policy by anyone else you permit to access the Service (such as a friend, family member, or guest.) Eagle Internet recommends against enabling file or printer sharing unless you do so in strict compliance with all security recommendations and features provided by the manufacturer of the applicable file or printer sharing devices. Any files or devices you choose to make available for shared access on a home LAN, for example, should be protected with a strong password or as otherwise appropriate. In all cases, you are solely responsible for the security of any device you connect to the Service, including any data stored or shared on that device. It is also your responsibility to secure the Customer Equipment and any other Premises equipment or programs not provided by Eagle Internet that connect to the Service from external threats such as viruses, spam, and other methods of intrusion.<br>
                Use of inappropriate content and transmissions<br>
                Eagle Internet reserves the right to refuse to transmit or post, and to remove or block, any information or materials, in whole or in part, that it, in its sole discretion, deems to be in violation of Sections I or II of this Policy, or otherwise harmful to Eagle Internet network or customers using the Service, regardless of whether this material or its dissemination is unlawful so long as it violates this Policy. Neither Eagle Internet nor any of its affiliates, suppliers, or agents have any obligation to monitor transmissions or postings (including, but not limited to, email, file transfer, blog, newsgroup, and instant message transmissions as well as materials available on the Personal Web Features as defined below) made on the Service. However, Eagle Internet and its affiliates, suppliers, and agents have the right to monitor these transmissions and postings from time to time for violations of this Policy and to disclose, block, or remove them in accordance with this Policy, any other Eagle Internet Agreements, or applicable law.
                Inappropriate electronic mail<br>
                The Service may not be used to communicate or distribute email or other forms of communications in violation of Section I of this Policy. As described below in Section III of this Policy, Eagle Internet uses reasonable network management tools and techniques to protect customers from receiving spam and from sending spam (often without their knowledge over an infected computer).
                Eagle Internet is not responsible for deleting or forwarding any email sent to the wrong email address by you or by someone else trying to send email to you. Eagle Internet is also not responsible for forwarding email sent to any account that has been suspended or terminated. This email will be returned to the sender, ignored, deleted, or stored temporarily at Eagle Internet sole discretion. If you cancel or terminate your Service account for any reason, all email associated with that account (and any secondary accounts) will be permanently deleted as well.
                <br>If Eagle Internet believes in its sole discretion that any subscriber name, account name, or email address (collectively, an “identifier”) on the Service may be used for, or is being used for, any misleading, fraudulent, or other improper or illegal purpose, Eagle Internet (i) reserves the right to block access to and prevent the use of any of these identifiers and (ii) may at any time require any customer to change his or her identifier. In addition, Eagle Internet may at any time reserve any identifiers on the Service for its own purposes.
                <br>Instant, video, and audio messages
                <br>Each user is responsible for the contents of his or her instant, video, and audio messages and the consequences of any of these messages. Eagle Internet assumes no responsibility for the timeliness, mis-delivery, deletion, or failure to store these messages. If you cancel or terminate your Service account for any reason, all instant, video, and audio messages associated with that account (and any secondary accounts) will be permanently deleted as well.
                Personal web pages and file storage
                <br>As part of the Service, Eagle Internet may provide access to personal web pages and storage space through personal web pages and online storage features (collectively, the “Personal Web Features”). You are solely responsible for any information that you or others publish or store on the Personal Web Features. You are also responsible for ensuring that all content made available through the Personal Web Features is appropriate for those who may have access to it. For example, you must take appropriate precautions to prevent minors from receiving or accessing inappropriate content. Eagle Internet reserves the right to remove, block, or refuse to post or store any information or materials, in whole or in part, that it, in its sole discretion, deems to be in violation of this Policy. For purposes of this Policy, “material” refers to all forms of communications including text, graphics (including photographs, illustrations, images, drawings, logos), executable programs and scripts, video recordings, and audio recordings. Eagle Internet may remove or block content contained on your Personal Web Features and terminate your Personal Web Features and/or your use of the Service if we determine that you have violated the terms of this Policy.
                <br>III. Network Management<br>
                Eagle Internet manages its network with one goal: to deliver the best possible broadband Internet experience to all of its customers. High-speed bandwidth and network resources are not unlimited. Managing the network is essential as Eagle Internet works to promote the use and enjoyment of the Internet by all of its customers. The company uses reasonable network management practices that are consistent with industry standards. Eagle Internet tries to use tools and technologies that are minimally intrusive and, in its independent judgment guided by industry experience, among the best in class. Of course, the company’s network management practices will change and evolve along with the uses of the Internet and the challenges and threats on the Internet. The need to engage in network management is not limited to Eagle Internet. In fact, all large internet service providers manage their networks. Many of them use the same or similar tools that Eagle Internet does. If the company didn’t manage its network, its customers would be subject to the negative effects of spam, viruses, security attacks, network congestion, and other risks and degradations of service. By engaging in responsible network management including enforcement of this Policy, Eagle Internet can deliver the best possible broadband Internet experience to all of its customers.
                Eagle Internet network management activities may include (i) identifying spam and preventing its delivery to customer email accounts, (ii) detecting malicious Internet traffic and preventing the distribution of viruses or other harmful code or content, (iii) temporarily lowering the priority of traffic for users who are the top contributors to current network congestion, and (iv) using other tools and techniques that Eagle Internet may be required to implement in order to meet its goal of delivering the best possible broadband Internet experience to all of its customers.
                <br>IV. Data Consumption<br>
                Eagle Internet is not currently applying a monthly data consumption threshold to EAGLE INTERNET Internet accounts. If the company changes that approach, it will post a new version of this Policy as described above and make other appropriate notifications to customers. Eagle Internet is providing versions of the Service with different speed and data consumption thresholds, among other characteristics, subject to applicable Service plans.
                <br>V. Violation of this Acceptable Use Policy<br>
                Eagle Internet reserves the right to immediately suspend or terminate your Service account and terminate the Subscriber Agreement if you violate the terms of this Policy or the Subscriber Agreement, or if anyone else you permit to access the Service violates this Policy. Eagle Internet does not routinely monitor the activity of individual Service accounts for violations of this Policy, except for determining aggregate data consumption in connection with Section IV of this Policy. However, in the company’s efforts to promote good citizenship within the Internet community, it will respond appropriately if it becomes aware of inappropriate use of the Service. Eagle Internet has no obligation to monitor the Service and/or the network. Eagle Internet and its suppliers reserve the right at any time to monitor bandwidth, usage, transmissions, and content in order to, among other things, operate the Service; identify violations of this Policy; and/or protect the network, the Service and Eagle Internet users. Eagle Internet prefers to inform customers of inappropriate activities and give them a reasonable period of time in which to take corrective action. Eagle Internet also prefers to have customers directly resolve any disputes or disagreements they may have with others, whether customers or not, without Eagle Internet intervention. However, if the Service is used in a way that Eagle Internet or its suppliers, in their sole discretion, believe violates this Policy, Eagle Internet or its suppliers may take any responsive actions they deem appropriate under the circumstances with or without notice. These actions include, but are not limited to, temporary or permanent removal of content, filtering of Internet transmissions, and the immediate suspension or termination of all or any portion of the Service. Neither Eagle Internet nor its affiliates, suppliers, or agents will have any liability for any of these responsive actions. These actions are not Eagle Internet exclusive remedies and Eagle Internet may take any other legal or technical actions it deems appropriate with or without notice.
                Eagle Internet reserves the right to investigate suspected violations of this Policy, including the gathering of information from the user or users involved and the complaining party, if any, and examination of material and data on Eagle Internet servers and network. During an investigation, Eagle Internet may suspend the account or accounts involved and/or remove or block material that potentially violates this Policy. You expressly authorize and consent to Eagle Internet and its suppliers cooperating with (i) law enforcement authorities in the investigation of suspected illegal violations, and (ii) and system administrators at other Internet service providers or other network or computing facilities in order to enforce this Policy. Upon termination of your Service account, Eagle Internet is authorized to delete any files, programs, data, email and other messages associated with your account (and any secondary accounts).
                <br> VI. Copyright<br>
                Eagle Internet is committed to complying with U.S. copyright and related laws, and requires all customers and users of the Service to comply with these laws. Accordingly, you may not store any material or content on, or access, share or disseminate any material or content over, the Service (or any part of the Service) in any manner that constitutes an infringement of third party intellectual property rights, including rights granted by U.S. copyright law. Eagle Internet provides an independent method for copyright owners to communicate information about alleged infringements to us, and for us to inform our customers about them: as described below, Eagle Internet complies with the Digital Millennium Copyright Act. You may receive alerts if your Service account is identified by a copyright owner as having been used in connection with acts of alleged copyright infringement.
                What is Eagle Internet DMCA policy?
                <br>Owners of copyrighted works who believe that their rights under U.S. copyright law have been infringed may take advantage of certain provisions of the Digital Millennium Copyright Act of 1998 (the “DMCA”) to report alleged infringements. It is Eagle Internet policy in accordance with the DMCA and other applicable laws to reserve the right to terminate the Service provided to any customer or user who is either found to infringe third party copyright or other intellectual property rights, including repeat infringers, or who Eagle Internet, in its sole discretion, believes is infringing these rights. Grounds for removal or termination include but are not limited to deleting or altering author attributes, copyright notices or other copyright management information unless expressly permitted in writing by the author or owner. Eagle Internet may terminate the Service at any time with or without notice for any affected customer or user.
                How do copyright owners report alleged infringements to Eagle Internet under the DMCA?
                Copyright owners may report alleged infringements of their works that are stored on the Service or the Personal Web Features by sending Eagle Internet authorized agent a notification of claimed infringement that satisfies the requirements of the DMCA. Upon Eagle Internet receipt of a satisfactory notice of claimed infringement for these works, Eagle Internet will respond expeditiously to either directly or indirectly (i) remove the allegedly infringing work(s) stored on the Service or the Personal Web Features or (ii) disable access to the work(s). Eagle Internet will also notify the affected customer or user of the Service of the removal or disabling of access to the work(s).
                Copyright owners may send Eagle Internet a notification of claimed infringement to report alleged infringements of their works under the DMCA (but not the Copyright Alerts System) to:
                <br>Eagle Internet / DMCA Notifications<br>
                <br>Email billing@eagleinternetservices.com<br>
                <br> Copyright owners may use their own notification of claimed infringement form that satisfies the requirements of Section 512(c)(3) of the U.S. Copyright Act. Under the DMCA, anyone who knowingly makes misrepresentations regarding alleged copyright infringement may be liable to Eagle Internet, the alleged infringer, and the affected copyright owner for any damages incurred in connection with the removal, blocking, or replacement of allegedly infringing material.
                If you receive a DMCA notification of alleged infringement as described above, and you believe in good faith that the allegedly infringing works have been removed or blocked by mistake or misidentification, then you may send a counter notification to Eagle Internet. Upon Eagle Internet receipt of a counter notification that satisfies the requirements of the DMCA, Eagle Internet will provide a copy of the counter notification to the person who sent the original notification of claimed infringement and will follow the DMCA’s procedures with respect to a received counter notification. In all events, you expressly agree that Eagle Internet will not be a party to any disputes or lawsuits regarding alleged copyright infringement.
                If a notification of claimed infringement has been filed against you, you can file a counter notification with Eagle Internet designated agent using the contact information shown above. All counter notifications must satisfy the requirements of Section 512(g)(3) of the U.S. Copyright Act.
                <br>  Revised and effective: April 1, 2020


            </p>
        </div>
    </section>

@endsection
