@extends('layouts.landing')
@section('content')


    <section class="pricing-area ptb-100 extra-mb pb-0"
             style="margin-bottom: 100px!important;background: rgba(211,211,211,0.15);padding-bottom: 30px!important;">
        <div class="container">
            <h2>Terms & Conditions</h2>
        </div>
    </section>



    <section class="services-area">
        <div class="container">
            <p>

                Fixed Wireless Terms & Conditions
                <br>
                <br>
                In consideration of the terms, conditions and covenants listed above in this contract (the “Contract”), the Customer (as indicated above) and Eagle Internet Services, LLC. agree as follows:
                <br>
                <span style="font-weight: bold">PURPOSE</span>: The Customer wishes to enter into a recurring contract with Eagle Internet for the provision of Internet service (“Services”) for the above-listed Service Address (the “Property”). In order to provide Services to the Property, Eagle Internet may install certain equipment and wiring at the Property.
                <br><span style="font-weight: bold">TERMS</span>: The Customer agrees that the term of this Contract starts on the date EAGLE INTERNET activates the Services and continues for the Initial Term.The Customer further agrees that the Contract shall automatically renew and continue for successive terms of one year (“Extension Terms”), unless Customer provides 30-day written notice to EAGLE INTERNET prior to the expiration of the Initial Term or any Extension Term, via email (billing@eagleinternetservices.com), or mail to Eagle Internet Services, LLC., P.O. Box 275, Demopolis, AL 36732, or the address Eagle Internet may designate from time to time. All Eagle Internet accounts require a 30 day notice.This is to include all month to month accounts and all term accounts.
                <br><span style="font-weight: bold">CREDIT CARD AUTHORIZATION</span>: Billing – Customer authorizes Eagle Internet to charge Customer’s credit card for the Services, and any and all charges due to Eagle Internet under the Contract. Eagle Internet will provide Customer with an itemized monthly statement by email describing all charges. If the Customer requests monthly statements via U.S. mail, then Eagle Internet shall add a $5.00 monthly fee for such service, in addition to the Monthly Recurring rate in this Contract. In the event Customer’s credit card, or other method of payment, fails to provide payment to Eagle Internet for any reason, Customer shall remain liable for amounts due under this Contract, and shall provide another card or method of payment to Eagle Internet.
                <br><span style="font-weight: bold">PAYMENT</span>: The installation fee and the first months service fee are due once the Services are activated. Payment may be made by credit card, debit card or check. Recurring monthly payments will be debited monthly using the debit card or credit card on file. Mailed invoices will be $5.00 in addition to monthly services fees.
                <br><span style="font-weight: bold">INSTALLATION FEES</span>: Customer shall pay for any installation fee(s) listed in this Contract.
                <br><span style="font-weight: bold">SERVICE FEES</span>: The Customer agrees to pay the monthly fee indicated above (“Monthly Recurring Rate”) for each month of Service. All payments are due 10 days after invoice date when paying by check or due upon receipt if paying by credit card. All payments received 5 days past due date will be considered late and subject to a $10 late fee. All accounts shut off for non-payment are subject to a reactivation fee of $25.00.
                <br><span style="font-weight: bold">INVOICES</span>: Single prices shown above for bundled Services, or for Services provided at multiple locations, will be allocated among the individual services for the purpose of applying applicable taxes and regulatory fees and also may be divided on the Customer’s invoice by location served.
                <br><span style="font-weight: bold">AUTHORIZATION</span>: Customer authorizes Eagle Internet, its employees, agents and independent contractors (“Authorized Parties”), to enter onto the Property to install and maintain any equipment and wiring necessary for Customer to receive the Services (collectively, “Permitted Equipment”). Customer represents and warrants to Eagle Internet that Customer has full authority to enter into this Contract, without obtaining approval of any other person, and acknowledges that Eagle Internet is relying upon such representation and warranty to proceed with installation of any required Permitted Equipment. Customer agrees to indemnify Eagle Internet for any liability arising out of or in any way connected to acts reasonably performed by Eagle Internet in reliance on Customer’s representations of authority. Additionally, in the event that Eagle Internet arrives on location for the installation of the Permitted Equipment, or activation of the Services, and the Customer does not or did not have the authority to authorize the installation, resulting in Eagle Internet having to remove equipment, relocate its equipment or reschedule the installation, Customer may be subject to a trip charge of ONE HUNDRED SEVENTY DOLLARS ($170.00).
                <br><span style="font-weight: bold">GUARANTEE OF SERVICE</span>: Eagle Internet offers “Asymmetrical”, “Symmetrical” and “Enterprise” plan types.“Asymmetrical” and “Symmetrical” are burstable plans.The upload and download speeds listed in the “Symmetrical” and “Asymmetrical” plan descriptions are Maximum Information Rates (MIRs).The Committed Information Rates (CIRs) for “Asymmetrical” and “Symmetrical” plans are 75% of the Maximum Information Rates (MIRs).The Committed Information Rates (CIRs) for “Enterprise” plans are 100% of the listed Maximum Information Rates (MIR’s). Eagle Internet also offers Tier Levels with support response guarantees for the Committed Information Rates.The details of any applicable service response guarantee may be found in the “Description of Packages” chart, which is available at www.Eagle Internet.com and details the respective onsite and telephone/email response guarantees for each Tier Package.
                <br><span style="font-weight: bold">UPGRADING OR DOWNGRADING SERVICE PLAN LEVELS</span>: The Customer may “Upgrade” to a higher “tier level” of Services at any time as well as “Downgrade” to a lower “tier level” of Services at any time. If Eagle Internet no longer offers the particular service or tier package utilized by the Customer following the expiration of the Contract Term or any Extension Term, Eagle Internet, in its sole discretion, shall place the Customer in the new service package which most closely approximates the package or tier which the Customer previously utilized. Further, Eagle Internet may change the terms of this Contract, including the above-referenced Monthly Recurring rate with 30 days written notice prior to the expiration of the Contract Term or any Extension Term.
                <br><span style="font-weight: bold">EQUIPMENT RECOVERY</span>: Upon termination of a Service for any reason, EAGLE INTERNET or its representative will contact Customer to schedule a mutually acceptable time and date for retrieval of Eagle Internet Equipment located on Customer’s premises. Alternatively, Eagle Internet may request that Customer package Eagle Internet Equipment and return it, at Eagle Internet cost, to a location identified by Eagle Internet. If Customer does not provide Eagle Internet with access to its premises to allow Eagle Internet to recover the Eagle Internet Equipment within thirty (30) days following Eagle Internet contact, or if Customer does not ship the Eagle Internet Equipment to Eagle Internet with the thirty (30) days, then Eagle Internet will charge Customer and Customer shall pay for the replacement cost of such equipment.
                <br> <span style="font-weight: bold">MOVING OR TRANSFERRING SERVICE</span>: In the event Customer moves locations within Eagle Internet coverage area, Customer shall pay ONE HUNDRED SEVENTY DOLLARS ($170) to transfer the Services to the new location (the “Move Order” fee).
                <br> <span style="font-weight: bold">ACCEPTABLE USE POLICY</span>: This Contract is subject to Eagle Internet Acceptable Use Policy (“AUP”), which is incorporated by reference herein and which may be modified from time to time at Eagle Internet sole discretion to improve network conditions, conform to industry standards and respond to legal and economic changes impacting the provision of the Services, as defined below. A copy of the AUP currently in effect may be found at www.Eagle Internet.com/AUP
                <br> <span style="font-weight: bold">FILTERING</span>: In the case of excessive bandwidth usage by peer to peer file sharing programs, compromised file servers or abusive packets originating from Customer’s connection, Eagle Internet reserves the right to throttle or shape Customer’s traffic to allow fair network conditions for its customers. All customers should realize this is in the best interest of business class connectivity.
                <br> <span style="font-weight: bold">ENTIRE SERVICE AGREEMENT</span>: SEVERABILITY – This Contract sets forth the entire understanding and agreement between Customer and Eagle Internet, and may be changed with written notice where expressly noted. In the event any provision of this Contract is found to be invalid, illegal or unenforceable, the validity, legality and enforceability of any of the remaining provisions shall not in any way be affected or impaired and a valid, legal and enforceable provision of similar intent and economic impact shall be substituted therefore.
                <br><span style="font-weight: bold">CHANGES IN CONTRACT TERMS</span>: We reserve the right to change the terms and conditions on which we offer Service. If we make any such changes, we will send you a copy of your new Customer Agreement containing its effective date. If you elect not to cancel your Service after receiving a new Customer Agreement, your continued receipt of Service constitutes acceptance of the changed terms and conditions. If you notify us that you do not accept such terms and conditions, then we may cancel your Service upon 30 days written notice to you, as we cannot offer Service to different customers on different terms, among other reasons. You will not be responsible for fees for early termination.
                <br><span style="font-weight: bold">LIMITATION OF LIABILITY</span>: The total cumulative liability of Eagle Internet, its employees, officers, directors, representatives and agents (hereinafter collectively called “the Eagle Internet parties”), if any, for costs, losses, or damages from all claims, actions or suits howsoever caused or arising out of or in connection with this agreement shall be limited to direct damages and shall not exceed the greater of: (i) the amount of payments received by Eagle Internet fromcustomer for the twelve months prior to the occurrence of the event(s) giving rise to any claims, actions or suits or (ii) any amounts payable and actually paid to the customer or Eagle Internet, as applicable, under any applicable insurance policies then in effect.In no event shall the EAGLE INTERNET parties or any member thereof be liable for any special, consequential, incidental, exemplary, punitive or other indirect damages, for loss of profits, loss of use or loss of data, howsoever caused or arising and regardless of legal theory or foreseeability.No claims may be asserted by either party against the other with respect to any act, event or omission that occurred more than eighteen (18) months prior to such claims, actions or suits being asserted.
                <br> <span style="font-weight: bold">ARBITRATION</span>: The parties agree that any disputes between the parties, their employees, their owners, officers or directors shall be resolved by binding arbitration pursuant to the Federal Arbitration Act.The arbitration shall be held in Lamar County, Texas and the arbitrator shall apply the substantive law of Texas, which shall govern this dispute. The parties shall share equally the cost of arbitration.
                <br> <span style="font-weight: bold">ATTORNEY’S FEES</span>: If either party brings legal action to enforce or interpret this Agreement, the prevailing party shall be entitled to its reasonable attorney’s fees and costs.
                <br> <span style="font-weight: bold">VENUE/ENTIRE AGREEMENT</span>: This Contract supersedes all prior agreements, if any. It can only be changed by a written agreement signed by parties. If any part of this Contract is deemed unenforceable, the remaining portions will continue in full force and effect. A waiver of a breach of any portion of this Contract will not be considered to be a waiver of any future breaches. This Contract will be governed by Texas law and any dispute will be venued in Lamar County, Texas.



            </p>
        </div>
    </section>

@endsection
